### PR TITLE
Fixed error wrapped twice in error tuple by the safe function.

### PR DESCRIPTION
**Pull request by acautin**

### CODE REVIEW

**Comment by acautin** [comment]
Current master:
```
 {error,
                                 {error,"c_src/dpiStmt_nif.c",47,
                                  #{action => "execute",code => 900,
                                    encoding => "UTF-8",
                                    fnName => "dpiStmt_execute",
                                    isRecoverable => false,
                                    message =>
                                     "ORA-00900: invalid SQL statement",
                                    offset => 0,sqlState => "HY000"}}}
```
This pr
```
{error,"c_src/dpiStmt_nif.c",47,
                                    #{action => "execute",code => 900,
                                      encoding => "UTF-8",
                                      fnName => "dpiStmt_execute",
                                      isRecoverable => false,
                                      message =>
                                          "ORA-00900: invalid SQL statement",
                                      offset => 0,sqlState => "HY000"}}
```

**Comment by c-bik** [comment]
@acautin process https://github.com/K2InformaticsGmbH/oranif/pull/110 into this PR first

**Comment by c-bik** [comment]
@acautin process https://github.com/K2InformaticsGmbH/oranif/pull/110 into this PR first (to help with the checks)

**Comment by acautin** [comment]
@c-bik thanks for the fix for the unit tests 👍

**Pull request merged**
